### ISSUE TITLE
panic: runtime error

### ISSUE THREAD

**Issue by crazy-matt** [andrewslotin/rummelsnuff#14]
Hi,

I got this error message today:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1a0 pc=0x66d2a7]

goroutine 1 [running]:
main.main()
	/go/github.com/andrewslotin/rummelsnuff/main.go:62 +0x3c7
```

Here is my config:

```
on:
  pull_request_target:
    branches: [main]
  push:
    branches: [ "**" ]
  workflow_dispatch:


defaults:
  run:
    shell: bash


jobs:
  cifirewalling:
    runs-on: ubuntu-latest
    steps:
      - name: Anti-PR-spam
        uses: andrewslotin/rummelsnuff@1.1.0
        with:
          spam_label: "spam"
          close_spam_prs: "yes"
          access_token: ${{ secrets.GITHUB_TOKEN }}
```
